function a = a_reactive(in1,in2,h,in4,in5,ph)
%A_REACTIVE
%    A = A_REACTIVE(IN1,IN2,H,IN4,IN5,PH)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Aug-2021 12:50:26

pw1 = in5(1,:);
pw2 = in5(2,:);
pw3 = in5(3,:);
pw4 = in5(4,:);
u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
w1 = in2(1,:);
w2 = in2(2,:);
w3 = in2(3,:);
w4 = in2(4,:);
t2 = 1.0./h;
t3 = pw1.*t2.*w1;
t4 = pw2.*t2.*w2;
t5 = pw3.*t2.*w3;
t6 = pw4.*t2.*w4;
t13 = ph.*2.0;
t7 = t3+t4+t5+t6-t13;
t8 = u1.^2;
t9 = u2.^2;
t10 = u3.^2;
t11 = u4.^2;
t12 = t8+t9+t10+t11;
t14 = sqrt(2.0);
t15 = sqrt(-h);
t16 = t7.*w1;
t17 = pw1.*t2.*t12.*(1.0./4.0);
t18 = t16+t17;
t19 = t7.*w2;
t20 = pw2.*t2.*t12.*(1.0./4.0);
t21 = t19+t20;
t22 = t7.*w3;
t23 = pw3.*t2.*t12.*(1.0./4.0);
t24 = t22+t23;
t25 = t7.*w4;
t26 = pw4.*t2.*t12.*(1.0./4.0);
t27 = t25+t26;
t28 = 1.0./t12;
a = [-t14.*t15.*t28.*(t18.*u1-t21.*u2-t24.*u3+t27.*u4);-t14.*t15.*t28.*(t18.*u2+t21.*u1-t24.*u4-t27.*u3);-t14.*t15.*t28.*(t18.*u3+t21.*u4+t24.*u1+t27.*u2);0.0];
