function H_opt = calculateHamiltonian(in1,in2,h,in4,in5,ph)
%CALCULATEHAMILTONIAN
%    H_OPT = CALCULATEHAMILTONIAN(IN1,IN2,H,IN4,IN5,PH)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Aug-2021 12:50:26

pu1 = in4(1,:);
pu2 = in4(2,:);
pu3 = in4(3,:);
pu4 = in4(4,:);
pw1 = in5(1,:);
pw2 = in5(2,:);
pw3 = in5(3,:);
pw4 = in5(4,:);
u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
w1 = in2(1,:);
w2 = in2(2,:);
w3 = in2(3,:);
w4 = in2(4,:);
t2 = 1.0./h;
t3 = pw1.*t2.*w1;
t4 = pw2.*t2.*w2;
t5 = pw3.*t2.*w3;
t6 = pw4.*t2.*w4;
t13 = ph.*2.0;
t7 = t3+t4+t5+t6-t13;
t8 = u1.^2;
t9 = u2.^2;
t10 = u3.^2;
t11 = u4.^2;
t12 = t8+t9+t10+t11;
t15 = t7.*w1;
t16 = pw1.*t2.*t12.*(1.0./4.0);
t17 = t15+t16;
t18 = t7.*w2;
t19 = pw2.*t2.*t12.*(1.0./4.0);
t20 = t18+t19;
t21 = t7.*w3;
t22 = pw3.*t2.*t12.*(1.0./4.0);
t23 = t21+t22;
t24 = t7.*w4;
t25 = pw4.*t2.*t12.*(1.0./4.0);
t26 = t24+t25;
t14 = t17.*u3+t20.*u4+t23.*u1+t26.*u2;
t27 = t17.*u1-t20.*u2-t23.*u3+t26.*u4;
t28 = t17.*u2+t20.*u1-t23.*u4-t26.*u3;
H_opt = pw1.*u1.*(-1.0./4.0)-pw2.*u2.*(1.0./4.0)-pw3.*u3.*(1.0./4.0)-pw4.*u4.*(1.0./4.0)+pu1.*w1+pu2.*w2+pu3.*w3+pu4.*w4+(sqrt(2.0).*sqrt(-h).*(t14.^2+t27.^2+t28.^2).*(1.0./2.0))./t12;
