function x = equitoctial2decart(in1,mug)
%EQUITOCTIAL2DECART
%    X = EQUITOCTIAL2DECART(IN1,MUG)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Jan-2025 14:04:06

L = in1(6,:);
ex = in1(2,:);
ey = in1(3,:);
ix = in1(4,:);
iy = in1(5,:);
p = in1(1,:);
t2 = cos(L);
t3 = sin(L);
t4 = ix.^2;
t5 = iy.^2;
t8 = 1.0./p;
t6 = ex.*t2;
t7 = ey.*t3;
t9 = -t5;
t10 = mug.*t8;
t11 = ix.*iy.*t2.*2.0;
t12 = ix.*iy.*t3.*2.0;
t13 = t4+t5+1.0;
t14 = t4+t9;
t15 = t6+t7+1.0;
t16 = sqrt(t10);
t17 = 1.0./t13;
t18 = t2.*t14;
t19 = t3.*t14;
t20 = 1.0./t15;
x = [p.*t17.*t20.*(t2+t12+t18);p.*t17.*t20.*(t3+t11-t19);p.*t17.*t20.*(ix.*t3-iy.*t2).*2.0;-t16.*t17.*(ey+t3-t11+t19+ey.*t14-ex.*ix.*iy.*2.0);-t16.*t17.*(-ex-t2+t12+t18+ex.*t14+ey.*ix.*iy.*2.0);t16.*t17.*(ex.*ix+ey.*iy+ix.*t2+iy.*t3).*2.0];
end
