function ortdgduv = get_ortdgdu(in1)
%GET_ORTDGDU
%    ORTDGDUV = GET_ORTDGDU(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 19:34:25

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
t2 = 1.0./u1;
ortdgduv = [-t2.*u4;t2.*u3;-t2.*u2;1.0];
