function dgduv = get_dgdu(in1)
%GET_DGDU
%    DGDUV = GET_DGDU(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 19:34:25

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
t2 = u1.*2.0;
t3 = u4.*2.0;
t4 = u2.*2.0;
dgduv = reshape([t2,t4,u3.*2.0,u2.*-2.0,t2,t3,u3.*-2.0,-t3,t2,t3,u3.*-2.0,t4],[3,4]);
