function F = get_target_g(in1,in2)
%GET_TARGET_G
%    F = GET_TARGET_G(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    18-Oct-2021 10:56:47

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
w1 = in2(1,:);
w2 = in2(2,:);
w3 = in2(3,:);
w4 = in2(4,:);
t2 = u1.^2;
t3 = u2.^2;
t4 = u3.^2;
t5 = u4.^2;
t6 = w1.^2;
t7 = w2.^2;
t8 = w3.^2;
t9 = w4.^2;
t14 = sqrt(2.0);
t10 = t6.*4.0;
t11 = t7.*4.0;
t12 = t8.*4.0;
t13 = t9.*4.0;
t15 = t2+t3+t4+t5;
t16 = 1.0./t15;
t17 = t10+t11+t12+t13+t15;
t18 = 1.0./t17;
t19 = sqrt(t18);
F = [t2-t3-t4+t5;u1.*u2.*2.0-u3.*u4.*2.0;u1.*u3.*2.0+u2.*u4.*2.0;t16.*(t14.*t19.*u1.*w1.*2.0-t14.*t19.*u2.*w2.*2.0-t14.*t19.*u3.*w3.*2.0+t14.*t19.*u4.*w4.*2.0);t16.*(t14.*t19.*u1.*w2.*2.0+t14.*t19.*u2.*w1.*2.0-t14.*t19.*u3.*w4.*2.0-t14.*t19.*u4.*w3.*2.0);t16.*(t14.*t19.*u1.*w3.*2.0+t14.*t19.*u3.*w1.*2.0+t14.*t19.*u2.*w4.*2.0+t14.*t19.*u4.*w2.*2.0)];
