function dgdu = get_dgdu(in1)
%GET_DGDU
%    DGDU = GET_DGDU(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Apr-2021 11:02:56

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
t2 = u2.^2;
t3 = u3.^2;
t4 = t2+t3;
t5 = 1.0./t4;
t6 = u1.^2;
t7 = u4.^2;
t8 = t6+t7;
t9 = 1.0./t8;
dgdu = reshape([u1.*2.0,0.0,-t9.*u4,0.0,u2.*2.0,-t5.*u3,0.0,u3.*2.0,t5.*u2,u4.*2.0,0.0,t9.*u1],[3,4]);
