function gv = get_gv(in1,in2)
%GET_GV
%    GV = GET_GV(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Apr-2021 15:36:20

V1 = in2(1,:);
V2 = in2(2,:);
V3 = in2(3,:);
v1 = in1(1,:);
v2 = in1(2,:);
v3 = in1(3,:);
v4 = in1(4,:);
t2 = V1.^2;
t3 = v1.^2;
t4 = v2.^2;
t5 = V2.^2;
t6 = v3.^2;
t7 = V3.^2;
t8 = v4.^2;
gv = [t3+t4+t6+t8,1.0./(t2+t5+t7).^2.*(t2.*t3-t2.*t4-t2.*t6-t3.*t5+t4.*t5+t2.*t8-t3.*t7+t4.*t7+t5.*t6-t5.*t8+t6.*t7-t7.*t8+V1.*V2.*v1.*v2.*4.0+V1.*V3.*v1.*v3.*4.0-V1.*V2.*v3.*v4.*4.0+V1.*V3.*v2.*v4.*4.0),angle(V1.*v1+V2.*v2+V1.*v4.*1i-V2.*v3.*1i+V3.*v2.*1i+V3.*v3)+angle(-V1.*v2+V2.*v1-V1.*v3.*1i+V3.*v1.*1i-V2.*v4.*1i+V3.*v4)];
