function dgdu = get_dgdu(in1)
%GET_DGDU
%    DGDU = GET_DGDU(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Sep-2021 00:08:47

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
t2 = u1.*2.0;
t3 = u2.*2.0;
t4 = u3.*2.0;
t5 = u4.*2.0;
t6 = -t4;
dgdu = reshape([t2,t3,t4,-t3,t2,t5,t6,-t5,t2,t5,t6,t3],[3,4]);
