function g = get_target_g(in1,in2)
%GET_TARGET_G
%    G = GET_TARGET_G(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Apr-2021 17:33:26

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
g = [u1.^2-u2.^2-u3.^2+u4.^2;u1.*u2.*2.0-u3.*u4.*2.0;u1.*u3.*2.0+u2.*u4.*2.0;u1.*v1-u2.*v2-u3.*v3+u4.*v4;u1.*v2+u2.*v1-u3.*v4-u4.*v3;u1.*v3+u3.*v1+u2.*v4+u4.*v2];
