function ortdgduv = get_ortdgduv(in1,in2)
%GET_ORTDGDUV
%    ORTDGDUV = GET_ORTDGDUV(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Apr-2021 17:33:27

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
ortdgduv = reshape([(u1.*u4)./(u1.*v2-u2.*v1),-(u1.*u3)./(u1.*v2-u2.*v1),(u1.*u2)./(u1.*v2-u2.*v1),-u1.^2./(u1.*v2-u2.*v1),(u1.*v4-u4.*v1)./(u1.*v2-u2.*v1),-(u1.*v3-u3.*v1)./(u1.*v2-u2.*v1),1.0,0.0,(u2.*u4)./(u1.*v2-u2.*v1),-(u2.*u3)./(u1.*v2-u2.*v1),u2.^2./(u1.*v2-u2.*v1),-(u1.*u2)./(u1.*v2-u2.*v1),(u2.*v4-u4.*v2)./(u1.*v2-u2.*v1),-(u2.*v3-u3.*v2)./(u1.*v2-u2.*v1),0.0,1.0],[8,2]);
