function prpV2pXpVX = prpV2pXpVXCylindric(in1,in2,in3,in4)
%PRPV2PXPVXCYLINDRIC
%    PRPV2PXPVX = PRPV2PXPVXCYLINDRIC(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    01-Sep-2021 21:04:14

V1 = in2(1,:);
V2 = in2(2,:);
pV1 = in4(1,:);
pV2 = in4(2,:);
pV3 = in4(3,:);
phi = in1(2,:);
pr1 = in3(1,:);
pr2 = in3(2,:);
pr3 = in3(3,:);
rho = in1(1,:);
t2 = cos(phi);
t3 = sin(phi);
prpV2pXpVX = [pr1.*t2+pr2.*t3-V2.*pV1.*t3+V2.*pV2.*t2,-pV1.*(V1.*t3+V2.*rho.*t2)+pV2.*(V1.*t2-V2.*rho.*t3)-pr1.*rho.*t3+pr2.*rho.*t2,pr3,pV1.*t2+pV2.*t3,-pV1.*rho.*t3+pV2.*rho.*t2,pV3];
