function prpV2pXpVX = prpV2pXpVXShperlingBurde(in1,in2,in3,in4)
%PRPV2PXPVXSHPERLINGBURDE
%    PRPV2PXPVX = PRPV2PXPVXSHPERLINGBURDE(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    08-Oct-2021 12:45:23

Vs1 = in2(1,:);
Vs2 = in2(2,:);
Vs3 = in2(3,:);
pV1 = in4(1,:);
pV2 = in4(2,:);
pV3 = in4(3,:);
pr1 = in3(1,:);
pr2 = in3(2,:);
pr3 = in3(3,:);
rs1 = in1(1,:);
rs2 = in1(2,:);
rs3 = in1(3,:);
t2 = rs1.^2;
t3 = rs2.^2;
t4 = rs3.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
t7 = t6.^3;
prpV2pXpVX = [pr1-Vs1.*pV1.*rs1.*t7-Vs2.*pV2.*rs1.*t7-Vs3.*pV3.*rs1.*t7,pr2-Vs1.*pV1.*rs2.*t7-Vs2.*pV2.*rs2.*t7-Vs3.*pV3.*rs2.*t7,pr3-Vs1.*pV1.*rs3.*t7-Vs2.*pV2.*rs3.*t7-Vs3.*pV3.*rs3.*t7,pV1.*t6,pV2.*t6,pV3.*t6];
