function sym_ddUdrdr = sym_ddUdrdr(in1)
%sym_ddUdrdr
%    sym_ddUdrdr = sym_ddUdrdr(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    10-Dec-2024 10:04:16

r1 = in1(1,:);
r2 = in1(2,:);
r3 = in1(3,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = r3.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5.^(5.0./2.0);
t7 = r1.*r2.*t6.*3.0;
t8 = r1.*r3.*t6.*3.0;
t9 = r2.*r3.*t6.*3.0;
sym_ddUdrdr = reshape([-t6.*(t2.*-2.0+t3+t4),t7,t8,t7,-t6.*(t2-t3.*2.0+t4),t9,t8,t9,-t6.*(t2+t3-t4.*2.0)],[3,3]);
end
