function f = symF_a0(in1,in2,h,in4,in5,ph,ptau)
%SYMF_A0
%    F = SYMF_A0(IN1,IN2,H,IN4,IN5,PH,PTAU)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Nov-2020 01:49:57

pu1 = in4(1,:);
pu2 = in4(2,:);
pu3 = in4(3,:);
pu4 = in4(4,:);
pv1 = in5(1,:);
pv2 = in5(2,:);
pv3 = in5(3,:);
pv4 = in5(4,:);
u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
f = [v1;v2;v3;v4;u1.*(-1.0./4.0);u2.*(-1.0./4.0);u3.*(-1.0./4.0);u4.*(-1.0./4.0);0.0;1.3271243994e20./conj((h.*-2.0).^(3.0./2.0));pv1.*(1.0./4.0);pv2.*(1.0./4.0);pv3.*(1.0./4.0);pv4.*(1.0./4.0);-pu1;-pu2;-pu3;-pu4;(ptau.*-3.981373198200001e20)./conj((h.*-2.0).^(5.0./2.0));0.0];
